language: go
sudo: false
notifications:
  email: false
  webhooks:
    urls:
      - http://status.bign8.info/api/ci/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.glide
env:
  global:
    - GOBENCH_URL=http://bench.bign8.info
    - GO111MODULE=on
