language: go
go: 1.8.x
notifications:
  email: false
  webhooks:
    urls:
      - http://status.bign8.info/api/ci/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.glide
env:
  - GOBENCH_URL=http://bench.bign8.info
